name: CI

on:
    push:
    pull_request:
    workflow_dispatch:
#    schedule:
#        - cron: '0 * * * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true


jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Create pages
        if: ${{ github.event_name != 'pull_request' }}
        run: |
            time wget --quiet https://static.crates.io/db-dump.tar.gz
            DIR=$(ls -d1 2023-* | head -n 1 | cut -d'/' -f1)
            mv "$DIR" "data"

            rustc --version
            cargo --version
            cargo run

      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1

  # Deployment job
  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

